### ISSUE TITLE
Flush location data when service stopped

### ISSUE THREAD

**Issue by nygma2004** [sellrik/GpsTracker#1]
With the email options, I wanted to record a specific activity, so I started and stopped the service. For me it appears that when the service is stopped, the location records for the last 30 minutes are still in the device and not send until the service started again later.

I think it would make sense to send the remaining data in an email when the service is stopped.

**Comment by sellrik** [comment]
I implemented this feature. The locations are sent after the logging is stopped. The upload process only runs once, if there is no network available it won't succeed (there is not retry logic).

**Comment by nygma2004** [comment]
Thanks, that means if this is running on a device with no mobile data, it is better to keep the job running and send the data when wifi is available again.
