### ISSUE TITLE
NetworkLogs structure missing ssid

### ISSUE THREAD

**Issue by nygma2004** [sellrik/GpsTracker#2]
Original idea was to identify location based on the wifi network. But for that to work the NetworkLogs structure should also include the SSID of the wifi network.

**Comment by sellrik** [comment]
I added the SSID to the NetworkLogs structure (also updated the apk).

**Comment by nygma2004** [comment]
Cool, let me test this tomorrow

**Comment by nygma2004** [comment]
Sorry, one more small detail. I prefer to use the timestamp field to retrieve the data and ignore the formatted DateTime field. The NetworkLogs does not contain the basic Time field (milliseconds passed since 01.01.1970). Could you please add that to the structure as well?

**Comment by sellrik** [comment]
Add a new Time field (it is also in UTC).

**Comment by nygma2004** [comment]
Good point, I should not forget to convert it to my local timezone.

**Comment by nygma2004** [comment]
One more request: when the phone disconnects from the wifi, the SSID field is empty. I am trying to keep track in the reporting which network the phone got disconnected from. But since the logs are coming in batches, it looks like it cannot be guaranteed that it gets processed in the same order as it happened. Therefore something is gets all messed up. 
I wanted to ask if it is possible for the phone to keep track of which network is was connected to and populate the SSID field when it disconnects from the wifi (IsConnected=0).

**Comment by sellrik** [comment]
I added the SSID to the disconnect log, and also added an identifier that should be unique for each connection. Hopefully it will work fine for you.

I am using this android component for the network monitoring: [NetworkCallback](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback)

I am not sure how reliable it is, but for me it seems to work fine most of the time.
However if you stop the loging for example, the disconnect log won't be created, and there might be similar issues.

**Comment by nygma2004** [comment]
It appears to be working for me too, without using the identifier of the connection. So I am relying on the SSID field for the time being. I can now separate the data into various tracks.
