### ISSUE TITLE
Gmail node is not working

### ISSUE THREAD

**Issue by K-ATS** [sellrik/GpsTracker#3]
Actually the Gmail node is not working I have already change the gmail setting and set on the allow less secure app, I am getting data from the mobile application and json file is also sent but in node red the Gmail node is not able to read attechment. 

![image](https://user-images.githubusercontent.com/96859006/149925830-8823492a-394f-45ed-8653-a0ec7a84f995.png)

**Comment by sellrik** [comment]
Please refer to Csongor Varga, he developed the node red flow. 
You can contact him on youtube: https://www.youtube.com/watch?v=ywljyO74MjE
Or on github: https://gist.github.com/nygma2004/fad2fff9d5a66fe3be672ec2287736b2

**Comment by sellrik** [comment]
@nygma2004

**Comment by nygma2004** [comment]
That is interesting, I have not used the email node for a while. I hope it did not change. 
Can you please do one test? Enable the 2 factor authentication again and generate an [App password](https://support.google.com/accounts/answer/185833?hl=en) in your Google account. That will generate a random password for you, and you can specify that in the email node. This will not affect your "main" google password, it will only be used by this node. This is how I used it as well. Please check if you see the same attachment issue.
